//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCollaborationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> SubtaskID { get; set; }
        public int InformationID { get; set; }
        public string Action { get; set; }
        public string HistoryStat { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Information Information { get; set; }
        public virtual Project Project { get; set; }
        public virtual Subtask Subtask { get; set; }
        public virtual Task Task { get; set; }
    }
}
